# Псевдо-сценарий! Работа данного плейбука не проверялась. Оставлено для наглядности
-
  name: Install Web
  hosts: all
  tasks:
    - command: service httpd status
      register: command_output

    - mail:
        to: Admins <system.admins@domain.com>
        subject: Service Alert
        body: "Httpd on {{ ansible_hostname }} is down"
        when: command_output.stdout.find("down") != -1