-
  name: Play1
  hosts: linux
  tasks:
    - name: Ping node
      ping:

    - name: Get Current OS Info
      command: "hostnamectl"
      register: os_info

    - name: Print command result
      debug:
        var: os_info.stdout_lines